/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 welcome.gltf --transform 
Files: welcome.gltf [67.84KB] > welcome-transformed.glb [16.72KB] (75%)
Author: Dominic Baker (https://sketchfab.com/Domuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/welcome-3d-text-logo-a37dfbce2d0a41c8a7491242be852daf
Title: Welcome 3D text logo
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/welcome-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Text_0" position={[2.953, 0.256, -0.003]}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.emission} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/welcome-transformed.glb')
